"""comments1

Revision ID: 403374d311cf
Revises: b76fad95d5d5
Create Date: 2018-09-18 09:19:33.753251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403374d311cf'
down_revision = 'b76fad95d5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blogs_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('dislike', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('like', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('ratings', sa.Integer(), nullable=True))
    op.drop_constraint('comments_blog_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'blogs', ['blogs_id'], ['id'])
    op.drop_column('comments', 'blog_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_blog_id_fkey', 'comments', 'blogs', ['blog_id'], ['id'])
    op.drop_column('comments', 'ratings')
    op.drop_column('comments', 'like')
    op.drop_column('comments', 'dislike')
    op.drop_column('comments', 'blogs_id')
    # ### end Alembic commands ###
